# Site settings
title: Hasil-Sharma
description: 'Life Long Learner, Data Science Enthusiast, Python Evangelist, Bibliophile'
url: "http://hasil-sharma.github.io"
baseurl: '/'
google_analytics: 'UA-98977358-1'
disqus_shortname: 'hasil-sharma-github-io'

author:
  name: 'Hasil Sharma'
  email: hasil.sharma7@gmail.com
  #twitter_username: 
  #facebook_username: hasil-sharma
  github_username:  hasil-sharma
  linkedin_username:  hasil-sharma

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate', 'jekyll-seo-tag']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
